@{
    Directories = 'Folders'
    Directory = 'Folder'
    Extensions = 'Extension'
    Exports = 'Export'
    ExtendedCommand = 'Extension'
    ExtendedCommands = 'Extension'
    Servers = 'Server'
    Domain  = 'Server'
    Domains = 'Server'
    Routes  = 'Route'
    Router  = 'Route'    
    Routers = 'Route'
    Assets = 'Asset'
}