@{
    Containers = 'Container'
    Directories = 'Folders'
    Directory = 'Folder'
    EntryPoints = 'EntryPoint'
    Extensions = 'Extension'
    Exports = 'Export'
    ExtendedCommand = 'Extension'
    ExtendedCommands = 'Extension'
    Servers = 'Server'
    Services = 'Service'    
    WebServices = 'Service'
    WebService = 'Service'
    WebCommands = 'Service'
    WebCommand = 'Service'    
    Domain  = 'Server'
    Domains = 'Server'
    Sites = 'Site'
    Website = 'Site'
    Websites = 'Site'
    Routes  = 'Route'
    Router  = 'Route'    
    Routers = 'Route'
    Assets = 'Asset'
}